### ISSUE TITLE
Feature Request - Amps usage measurement

### ISSUE THREAD

**Issue by hblanken** [xorbit/LiFePO4wered-Pi#11]
I am very much looking forward to the new 2A module! Hope you are ready soon, you got one buyer for sure 👍 
Could you add a Amps usage measurement to your cli software as well? That would be a very valuable feature to see how much each board/usb etc is chewing up. Or how else could I quickly see the A usage?

**Comment by xorbit** [comment]
Thanks! The next gen module will have output current readout from the CLI software available. :)
