### ISSUE TITLE
Multiple batteries?

### ISSUE THREAD

**Issue by ErroneousBosch** [xorbit/LiFePO4wered-Pi#13]
Fantastic product, I plan on buying one in the near future. Would this kind of circuit be able to handle multiple 18650s wired in parallel for increased capacity?

**Comment by xorbit** [comment]
Yes, this works and has been done by multiple customers.  You need to make sure their state of charge is very close when you connect them in parallel so no high currents flow between the cells.  But once connected, they act like a large virtual cell.
Charge current will still be the same, so charging will take longer with a bigger cell of course.
