### ISSUE TITLE
Replace battery?

### ISSUE THREAD

**Issue by StoneISStephan** [xorbit/LiFePO4wered-Pi#18]
Hi,

could I replace the battery on the LiFePO4wered/Pi3 with a bigger capacity one, say a Panasonic NCR18650B?

**Comment by xorbit** [comment]
Hello,

You can replace the cell with another LiFePO4 cell, but not with another chemistry.  The NCR cell is another chemistry that's not compatible.  LiFePO4 cells start with IFR or APR.
