### ISSUE TITLE
How to use the RPI UART with  LiFePO 4 wered/Pi™  connected

### ISSUE THREAD

**Issue by biank88** [xorbit/LiFePO4wered-Pi#2]
I think that it's not mentioned in the documentation if it would be possible to use the UART module and the lifepo4weredPi at the same time.

**Comment by xorbit** [comment]
It mostly is an issue of getting the UART physically connected.  If you can connect to it by extending the pins or soldering a wire to it, you can use the UART.  The LiFePO4wered/Pi only uses the UART TX pin to detect shutdown.

**Comment by biank88** [comment]
That's nice! Thank you very much.
BTW I'm asking these questions here on Github, instead of asking them privately, so that they might be useful for somebody else. I hope this is not a problem for you.
