### ISSUE TITLE
Detecting source power state

### ISSUE THREAD

**Issue by kozuch** [xorbit/LiFePO4wered-Pi#21]
Is is possible to detect/query the voltage on USB charge connector? I need just to safely power down RPi when source (=charging?) power is disconnected LiFePO4wered-Pi. I could not find this in the docs.

**Comment by xorbit** [comment]
The original LiFePO4wered/Pi is missing the hardware to be able to do this.  Both the LiFePO4wered/Pi3 and upcoming LiFePO4wered/Pi+ do have this feature.  You can get the input voltage directly or use auto boot and auto shutdown features based on it.
