### ISSUE TITLE
Question: Best way to add push notification / logging on power drop/restore and shutdown action

### ISSUE THREAD

**Issue by evertide** [xorbit/LiFePO4wered-Pi#23]
Hi,

What would be the best way to get some logging on power drops, restores, and daemon clean shutdowns.

I am looking to implement a push notification ( pushover) to get some more grip on what is happening.

regards

**Comment by xorbit** [comment]
Not sure about the "best way".  The daemon logs to syslog, maybe you can tap into that.  For the rest, a script or program can read the status of VIN and log when a change is detected.
