### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by daghemo** [xorbit/LiFePO4wered-Pi#29]
The installation process seems not to be compatible with Python 3, because of fabricate.py.

I've seen that the work has been done by @smurfix within pull #28, but all that commits has been merged into py3-systemd-pkg branch.

May you can take only commit 796215c8568e12baf54f2d8de6c9604c976de59a into the master branch.

Some link on the subject:
http://python3porting.com/noconv.html
https://python-future.org/compatible_idioms.html
https://docs.python.org/3.3/howto/pyporting.html

**Comment by xorbit** [comment]
Fixed by #46.
All Python dependency has been removed from the build system.
