### ISSUE TITLE
stime function removed from glibc 2.31

### ISSUE THREAD

**Issue by taaaaaad** [xorbit/LiFePO4wered-Pi#34]
the stime function has been removed from glibc 2.31, and replaced with clock_settime.  
[https://wiki.gentoo.org/wiki/Glibc_2.31_porting_notes/stime_removal](url)

This is apparently now the version shipping in Ubuntu for Pi 20.04, giving the following error:
lifepo4wered-daemon.c:(.text+0x15a): undefined reference to `stime'

**Comment by xorbit** [comment]
Fixed by #46.
