### ISSUE TITLE
Best way to uninstall?

### ISSUE THREAD

**Issue by roens** [xorbit/LiFePO4wered-Pi#4]
Hi,

This is great. But after giving it a try on an RPi2, then deciding the power requirements on that particular machine exceed what LiFePO4wered-Pi can handle, removed it. What's the best way to "uninstall" the software component? Just delete these & reboot?
```
/usr/local/sbin/lifepo4wered-daemon
/usr/local/bin/lifepo4wered-cli
/run/systemd/generator.late/lifepo4wered-daemon.service
/run/systemd/generator.late/runlevel5.target.wants/lifepo4wered-daemon.service
/run/systemd/generator.late/runlevel4.target.wants/lifepo4wered-daemon.service
/run/systemd/generator.late/runlevel3.target.wants/lifepo4wered-daemon.service
/run/systemd/generator.late/runlevel2.target.wants/lifepo4wered-daemon.service
/etc/init.d/lifepo4wered-daemon
```

**Comment by xorbit** [comment]
Leaving them doesn't hurt anything, but yes if you want to uninstall, you can delete:
```
/usr/local/sbin/lifepo4wered-daemon
/usr/local/bin/lifepo4wered-cli
/usr/local/lib/liblifepo4wered.so
/etc/init.d/lifepo4wered-daemon
```
I'm not sure if you need to manually remove the `/run/systemd` entries.  I don't install them, they are generated by systemd from the init script, and I'm not sure if they are also automatically removed or not.

**Comment by roens** [comment]
Thanks! 😀
