### ISSUE TITLE
No power provided

### ISSUE THREAD

**Issue by jonach66** [xorbit/LiFePO4wered-Pi#47]
Hi there XORBIT,

I´m using 2 LiFePo4+, one of them works great, the other one is not working properly. My register dump is:

```
I2C_REG_VER = 7
I2C_ADDRESS = 67
LED_STATE = 1
TOUCH_STATE = 0
TOUCH_CAP_CYCLES = 0
TOUCH_THRESHOLD = 12
TOUCH_HYSTERESIS = 2
DCO_RSEL = 14
DCO_DCOMOD = 156
VIN = 5091
VBAT = 3323
VOUT = 5004
IOUT = 141
VBAT_MIN = 2850
VBAT_SHDN = 2950
VBAT_BOOT = 3150
VOUT_MAX = 3500
VIN_THRESHOLD = 4250
IOUT_SHDN_THRESHOLD = 0
VBAT_OFFSET = 59
VOUT_OFFSET = 41
VIN_OFFSET = 50
IOUT_OFFSET = 0
AUTO_BOOT = 0
WAKE_TIME = 0
SHDN_DELAY = 40
AUTO_SHDN_TIME = 65535
PI_BOOT_TO = 300
PI_SHDN_TO = 120
RTC_TIME = 458
RTC_WAKE_TIME = 0
WATCHDOG_CFG = 0
WATCHDOG_GRACE = 20
WATCHDOG_TIMER = 20
PI_RUNNING = 1
CFG_WRITE = 0
```

Problem description:
- PI (Zero) starts & runs when power is supplied via LiFePo4+-USB
- battery is charged endless... (battery works, tested with the second LiFePo4+)
- if LiFePo4+-USB power is removed, PI loses power suddenly...

It seems there is no power supply from battery to PI. Any recommendations what tests or measurements I should try?

Kind regards!
Jo

**Comment by xorbit** [comment]
Hello Jo,
Sorry to hear you're having a problem with your unit.
This seems to be very much a hardware problem though, and this issue tracker is for the host software.  Can you send an email to support@lifepo4wered.com, and I will take it from there?
Thanks!
