### ISSUE TITLE
REQ: Autoshutdown

### ISSUE THREAD

**Issue by madeinoz67** [xorbit/LiFePO4wered-Pi#5]
I'd like the ability to perform auto shutdown of Pi if incoming power is disconnected.  e.g. shutdown after x delay when incoming power in not present.

**Comment by xorbit** [comment]
This is a feature that has been requested frequently, and as you can see in the code, it has been added to the host code already!  Look for AUTO_SHDN_TIME, which has been added to register version 4.  As this requires hardware support, it will first be available in the new LiFePO4wered/Pi3 that will hopefully be released later this week.  I'm hoping to backport this to future versions of the LiFePO4wered/Pi as well.

**Comment by madeinoz67** [comment]
awesome, can the current version hardware be modded to take advantage of the autoshutdown?

**Comment by xorbit** [comment]
Unfortunately not easily.  The original LiFePO4wered/Pi power manager is missing a connection from the 4-pin header to the microcontroller and the charger part doesn't have the correct resistive divider.
