### ISSUE TITLE
Reboot of the RPI blocked with the LiFePO4wered/Pi+ abd CLI

### ISSUE THREAD

**Issue by Lunik971** [xorbit/LiFePO4wered-Pi#57]
hello,

I have a issue with the LiFePO4wered/Pi+ and the programm, when I send a reboot command the system just shutdown and do not comme up.
Does I have a setting to chagne for that ?

Issue :
1 : Send Reboot command
2 : The system power off
3 : The RPI never power on, need to press the button to power on again.

**Comment by xorbit** [comment]
Most likely the issue can be fixed using the SHDN_DELAY register.  The problem most likely is that the newer Pis take much more time in the bootloader than old Pis.  The default value for SHDN_DELAY was appropriate for the older Pis but is too short for the newer ones.  The delay basically sets a wait time after the kernel shut down before power is removed, and a reboot can set TX high again to keep the system running through a reboot, if it waits long enough.

If you run `lifepo4wered-cli get SHDN_DELAY` you can see the current value of the register.  Most likely it's the old default value of 40.  Use `lifepo4wered-cli set SHDN_DELAY 64` to set it to the new higher default value and see if that fixes the issue.  If you want to make it permanent by writing it to flash, also run `lifepo4wered-cli set CFG_WRITE 70`.

**Comment by xorbit** [comment]
Did this fix your issue?  If so, please close this issue.

**Comment by Lunik971** [comment]
Hello,
Sorry for the late answer, ans yes this solved m'y issue.
Many thanks
