### ISSUE TITLE
Start operations times out

### ISSUE THREAD

**Issue by wickflair23** [xorbit/LiFePO4wered-Pi#58]
Just received my device and I am having issues getting it to work with my Pi 3 b+. 
Running YoDeck software via their Raspbian Buster 10 image with custom packages. 

Looking at the logs I see. 

lifepo4wered-daemon.service: Start operation timed out. Terminating.

Which is exactly what I assumed the issue was due to the green power light always flashing and never stopping until the Pi Powers off. Everything is running fine while it's attempting to boot.  I have tried a fresh install with no luck.

**Comment by xorbit** [comment]
Issue was diagnosed over email and was related to lack of `/dev/i2c*` devices being created on a customized distro.
