### ISSUE TITLE
logging support

### ISSUE THREAD

**Issue by elevatorguy** [xorbit/LiFePO4wered-Pi#64]
This may run as expected `lifepo4wered-cli get >> file.log`, but put it in `file.sh` and call it via cron, then it may not. Is this a code change or a script issue?

**Comment by xorbit** [comment]
Hmm, odd.  Is the script run as a user that has I2C bus access?

**Comment by xorbit** [comment]
Hi were you able to resolve this issue?

**Comment by xorbit** [comment]
Closing due to lack of comments, assumed resolved.
